<?php
/**
 * @category    Ms
 * @package     Ms_AddressVerification
 * @license     https://markshust.com/eula/
 */
if($this->getIsShipping()):
    $_fieldsContainerId = 'order-shipping_address_fields';
    $_addressChoiceContainerId = 'order-shipping_address_choice';
    ?>
    <script type="text/javascript">
    order.shippingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    order.setAddresses(<?php echo $this->getAddressCollectionJson() ?>);
    </script>
    <?php
else:
    $_fieldsContainerId = 'order-billing_address_fields';
    $_addressChoiceContainerId = 'order-billing_address_choice';
    ?>
    <script type="text/javascript">
    order.billingAddressContainer = '<?php echo $_fieldsContainerId ?>';
    </script>
    <?php
endif; ?>
<div class="entry-edit">

    <div class="entry-edit-head">
        <h4 class="icon-head fieldset-legend <?php echo $this->getHeaderCssClass() ?>"><?php echo $this->getHeaderText() ?></h4>
     </div>

    <fieldset class="np">
    <div id = "<?php echo $_addressChoiceContainerId ?>" class="order-choose-address">
        <?php echo Mage::helper('sales')->__('Select from existing customer addresses:') ?><br/>
        <?php $_id = $this->getForm()->getHtmlIdPrefix() . 'customer_address_id' ?>
        <select id="<?php echo $_id ?>"  name="<?php echo $this->getForm()->getHtmlNamePrefix()?>[customer_address_id]" style="width:97.5%;" onchange="order.selectAddress(this, '<?php echo $_fieldsContainerId ?>')">
            <option value=""><?php echo Mage::helper('sales')->__('Add New Address') ?></option>
            <?php foreach ($this->getAddressCollection() as $_address): ?>
            <?php //if($this->getAddressAsString($_address)!=$this->getAddressAsString($this->getAddress())): ?>
            <option value="<?php echo $_address->getId() ?>"<?php if ($_address->getId()==$this->getAddressId()): ?> selected="selected"<?php endif; ?>>
                <?php echo $this->getAddressAsString($_address) ?>
            </option>
            <?php //endif; ?>
            <?php endforeach; ?>

        </select>
        <br/>
        <?php if($this->getIsShipping()): ?>
            <input type="checkbox" id="order-shipping_same_as_billing" name="shipping_same_as_billing" onclick="order.setShippingAsBilling(this.checked)" <?php if($this->getIsAsBilling()): ?>checked<?php endif; ?>/>
            <label for="order-shipping_same_as_billing" class="no-float"><?php echo Mage::helper('sales')->__('Same As Billing Address') ?></label>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </div>

    <div class="order-address" id="<?php echo $_fieldsContainerId ?>">
        <div class="content">
            <?php echo $this->getForm()->toHtml() ?>
        </div>
        <div class="order-save-in-address-book">
            <?php if (Mage::getStoreConfig('ms_addressverification/general/enabled')): ?>
            <div style="padding-bottom:5px;">
                <button id="validate_address" onclick="<?php echo str_replace('-', '', $this->getForm()->getHtmlIdPrefix()) ?>validateAddress()" class="scalable " type="button" title="Validate Address">
                    <span><span><span>Validate Address</span></span></span>
                </button>
                <span id="<?php echo $this->getForm()->getHtmlIdPrefix()?>validate_address_response" style="padding-left:10px;"></span>
            </div>
            <?php endif; ?>
            <input name="<?php echo $this->getForm()->getHtmlNamePrefix()?>[save_in_address_book]" type="checkbox" id="<?php echo $this->getForm()->getHtmlIdPrefix()?>save_in_address_book" value="1" <?php if (!$this->getDontSaveInAddressBook() && $this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?>/>
            <label for="<?php echo $this->getForm()->getHtmlIdPrefix()?>save_in_address_book"><?php echo Mage::helper('sales')->__('Save in address book') ?></label>
        </div>
    </div>
    <?php $hideElement = 'address-' . ($this->getIsShipping() ? 'shipping' : 'billing') . '-overlay'; ?>
    <div style="display:none;" id="<?php echo $hideElement ?>" class="overlay"><span><?php echo $this->__('Shipping address selection is not applicable') ?></span></div>
    <script type="text/javascript">
        order.bindAddressFields('<?php echo $_fieldsContainerId ?>');
        order.bindAddressFields('<?php echo $_addressChoiceContainerId ?>');
        <?php if($this->getIsShipping() && $this->getIsAsBilling()): ?>
        order.disableShippingAddress(true);
        <?php endif; ?>

        <?php if (Mage::getStoreConfig('ms_addressverification/general/enabled')): ?>
        <?php echo str_replace('-', '', $this->getForm()->getHtmlIdPrefix()) ?>validateAddress = function(){
            var prefix = "<?php echo $this->getForm()->getHtmlIdPrefix()?>"
            var street0El = $(prefix + 'street0')
            var street1El = $(prefix + 'street1')
            var cityEl = $(prefix + 'city')
            var regionIdEl = $(prefix + 'region_id')
            var postcodeEl = $(prefix + 'postcode')
            var countryIdEl = $(prefix + 'country_id')

            // Handle sending ajax request to verify address with USPS
            new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('adminhtml/addressverification_ajax/index/index') ?>', {
                parameters: {
                    street0: street0El.value,
                    street1: street1El.value,
                    city: cityEl.value,
                    region_id: regionIdEl.value,
                    postcode: postcodeEl.value,
                    country_id: countryIdEl.value
                },
                onSuccess: function(response){
                    response = JSON.parse(response.responseText)

                    var responseEl = $('<?php echo $this->getForm()->getHtmlIdPrefix()?>validate_address_response')

                    responseEl.update(response.message);

                    if (response.error) {
                        responseEl.setStyle({color: 'red'})
                    } else {
                        responseEl.setStyle({color: 'green'})

                        street0El.value = response.street0[0]
                        if (response.street1[0]) street1El.value = response.street1[0]
                        cityEl.value = response.city[0]
                        regionIdEl.value = response.region_id
                        postcodeEl.value = response.postcode
                        countryIdEl.value = response.country_id

                        if ($('order-shipping_same_as_billing').checked) {
                            order.copyDataFromBillingToShipping(street0El)
                            order.copyDataFromBillingToShipping(street1El)
                            order.copyDataFromBillingToShipping(cityEl)
                            order.copyDataFromBillingToShipping(regionIdEl)
                            order.copyDataFromBillingToShipping(postcodeEl)
                            order.copyDataFromBillingToShipping(countryIdEl)
                        }
                    }
                }
            })
        }
        <?php endif; ?>
    </script>
    </fieldset>
</div>
