<?php

?>
<div class="yotpo bottomLine"
    data-appkey="d8jBYdxpgfwdMFZOufoSX6M494KJXLmQa66UEkgO"
    data-product-id="<?php echo $this->getProductId() ?>"
    data-name="<?php echo $this->getProductName() ?>"
    data-url="<?php echo $this->getProductUrl() ?>"   
    data-image-url="<?php echo $this->getProductImageUrl() ?>"
    data-description="<?php echo $this->getProductDescription() ?>">
</div>