<?php if (!Mage::getStoreConfig('yotpo/yotpo_general_group/disable_default_widget_position',Mage::app()->getStore())):?>
	<?php
	$pid = $this->getProductId();
	$url = 'http://staticw2.yotpo.com/batch';
	$data = array('methods' => '[{"method":"main_widget","params":{"pid":"'.$pid.'"}}]',
		'app_key' => $this->getAppKey());

	$options = array(
		'http' => array(
			'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
			'method'  => 'POST',
			'content' => http_build_query($data),
		),
	);
	$context  = stream_context_create($options);
	$result = file_get_contents($url, false, $context);
	// Parsing the response
	$response = json_decode($result, true);
	// echo '<pre>'; print_r($options);die;
	$main_widget = $response[0]["result"];
	?>
	<div class="yotpo yotpo-main-widget"
		 data-appkey="<?php echo $this->getAppKey(); ?>"
		 data-product-id="<?php echo $this->getProductId() ?>"
		 data-name="<?php echo $this->getProductName() ?>"
		 data-url="<?php echo $this->getProductUrl() ?>"
		 data-image-url="<?php echo $this->getProductImageUrl() ?>"
		 data-description="<?php echo $this->getProductDescription() ?>">
		<?php echo $main_widget ?>
	</div>
<?php endif ?>