<?php if (!Mage::getStoreConfig('yotpo/yotpo_general_group/disable_default_widget_position',Mage::app()->getStore())):?>
    <?php
    $url = 'http://staticw2.yotpo.com/batch';
    $data = array('methods' => '[{"method":"testimonials","params":{"format": "html"}}]',
        'app_key' => $this->getAppKey());

    $options = array(
        'http' => array(
            'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
            'method'  => 'POST',
            'content' => http_build_query($data),
        ),
    );
    $context  = stream_context_create($options);
    $result = file_get_contents($url, false, $context);
    // Parsing the response
    $response = json_decode($result, true);
    // echo '<pre>'; print_r($options);die;
    $testimonials = $response[0]["result"];
    ?>
    <div class="yotpo testimonials">
        <?php echo $testimonials ?>
    </div>
<?php endif ?>