<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<?php
	$meigee_harbour_general = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_general');
	$meigee_harbour_appearance = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_appearance');
    $logo = $meigee_harbour_appearance['logo'];
    $mediaurl = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('mediaurl');
	$customer = Mage::getSingleton('customer/session');
	$stickyStatus = $meigee_harbour_appearance['header']['floatingheader'];
?>

<header id="sticky-header" class="floating header">
	<div class="menu-line">
		<div class="container_12">
			<div class="grid_12">
				<?php if(isset($logo['small_logo'])): ?>
					<h2 class="small-logo"><strong><?php echo $logo['logo_alt']; ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $logo['logo_alt']; ?>" class="logo"><img src="<?php echo $mediaurl.$logo['small_logo']; ?>" <?php echo MAGE::helper('ThemeOptionsHarbour/Retina')->getRetinaData('small_logo'); ?> alt="<?php echo $logo['logo_alt']; ?>" /></a></h2>
				<?php else : ?>
					<h2 class="small-logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getSkinUrl('images/small_logo.png') ?>" <?php echo MAGE::helper('ThemeOptionsHarbour/Retina')->getRetinaData('default_small_logo'); ?> alt="<?php echo $this->getLogoAlt() ?>" /></a></h2>
				<?php endif; ?>
				<div class="header-right">
					<?php echo $this->getChildHtml('topMenu') ?>
					<div class="search-button">
						<?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('search'); ?>
					</div>
					<?php echo $this->getChildHtml('topSearch') ?>
					<?php echo $this->getChildHtml('cart_sidebar'); ?>
					<div class="menu-button"><span><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('mobilemenu'); ?><?php echo $this->__('Menu'); ?></span></div>
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</header>