<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2017 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php $linkButtons = $this->getLinkButtons(); ?>
<?php if (count($linkButtons)) : ?>

<div class="pslogin-unlinked-buttons pslogin-buttons <?php if ($this->showFull()): ?>pslogin-buttons-showfull<?php endif; ?>">
    <ul class="pslogin-clearfix">
    <?php $i = 0; ?>
    <?php foreach ($linkButtons as $button) : ?>
        <li class="pslogin-button <?php echo $button['type']; ?> pslogin-visible <?php if ($i >= 8): ?>pslogin-hidden<?php endif; ?>" <?php if ($i >= 8): ?>style="display:none;"<?php endif; ?> title="<?php echo $this->escapeHtml($button['link_text']); ?>">
            <?php $href = Mage::getUrl('pslogin/account/use', array('type' => $button['type'], 'call' => 'pslogin.account.link')); ?>
            <a class="pslogin-button-link" rel="nofollow" href="javascript:void(0);" onclick="psLogin('<?php echo $href; ?>', '<?php echo $button['popup_width']; ?>', '<?php echo $button['popup_height']; ?>');" >
                <span class="pslogin-button-auto <?php echo !empty($button['image']['login'])? 'pslogin-has-button-image' : ''; ?> <?php echo !empty($button['image']['icon'])? 'pslogin-has-button-icon-image' : ''; ?>">
                    <span class="pslogin-button-icon">
                        <?php echo !empty($button['image']['icon'])? '<img class="pslogin-button-icon-image" src="'. $this->escapeHtml($button['image']['icon']) .'" />' : ''; ?>
                    </span>
                    <span class="pslogin-button-text"><?php echo $this->escapeHtml($button['link_text']); ?></span>
                </span>
            </a>
        </li>
        <?php $i++; ?>
    <?php endforeach; ?>
    </ul>

    <?php if ($i >= 8): ?>
        <div class="pslogin-spacer pslogin-clearfix pslogin-showmore">
            <table>
                <tr>
                    <td><div class="pslogin-border"></div></td>
                    <td class="w100"><div class="pslogin-showmore-button pslogin-bordertext"><?php echo $this->__('show more'); ?></div></td>
                    <td><div class="pslogin-border"></div></td>
                </tr>
            </table>
        </div>
    <?php endif; ?>
    <div style="clear: both;"></div>

</div>
<?php endif;