<?php
/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_Jet
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
  
$category_level_0 = $this->getFilteredJetCollection(0);
$category_level_1 = $this->getFilteredJetCollection(1);
$category_level_2 = $this->getFilteredJetCollection(2);


$jetNodeId = "";
$profile = Mage::registry('current_profile');
if ($profile) {
    $jetNodeId = $profile->getData('node_id');
}


$current_id = $jetNodeId;

$parent = '';
$root = '';
$child = '';

//var_dump($category_list->getData());die;

$level_2 = array();
foreach ($category_level_2->getData() as $arr) {
    if ($arr['csv_cat_id'] == $current_id) {
        $child = $arr['csv_cat_id'];
        $parent = $arr['csv_parent_id'];
    }
    $level_2[$arr['csv_parent_id']][$arr['csv_cat_id']] = $arr['name'];
}
$json_subchild_arr = json_encode($level_2);

$level_1 = array();
foreach ($category_level_1->getData() as $arr) {
    if (($parent != '') && ($arr['csv_cat_id'] == $parent)) {
        $root = $arr['csv_parent_id'];
    } elseif ($arr['csv_cat_id'] == $current_id) {
        $parent = $arr['csv_cat_id'];
        $root = $arr['csv_parent_id'];
    }

    $level_1[$arr['csv_parent_id']][$arr['csv_cat_id']] = $arr['name'];
}
$json_child_arr = json_encode($level_1);

$level_0 = array();
foreach ($category_level_0->getData() as $arr) {
    $level_0[$arr['csv_cat_id']] = $arr['name'];
}
$json_parent_arr = json_encode($level_0);
?>

<div style="" id="category_info_tabs_jet_categorymapping_content">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Jet Category Mapping</h4>
            <div class="form-buttons"></div>
        </div>
        <div id="custom_category_tab_form" class="fieldset ">
            <?php //$root_cat_id = Mage::registry('current_category')->getParentId();

            $root_cat_id = 2;//enhancement

            if ($root_cat_id == '' || $root_cat_id == 0 || $root_cat_id == 1) { ?>
                <p>Select Sub Category , Jet does not allow to map with root category. </p>
            <?php }
            ?>
            <?php
            if ($root_cat_id != '' && $root_cat_id != 0 && $root_cat_id != 1) { ?>
                <p>Select Preferred Jet Category to be Mapped </p>
                <div class="hor-scroll" id="pro">
                    <input type="hidden" name="node_id" id="custom_tab_text" value="">
                    <!-- <input type="hidden" class=" input-text" value="" name="custom_tab_text" id="custom_tab_text"> -->
                </div>
            <?php }
            ?>

        </div>
    </div>
</div>

<script type="text/javascript">
    var isAjaxRunning = false;

    function updateCategoryAttribute() {

        <?php
        $profileId = '0';
        if ($profile && $profile->getId()) {
            $profileId = $profile->getId();
        }
        ?>
        var nodeId = document.getElementById('custom_tab_text').value;


        // var csloader = new varienLoader();
        /*if(isAjaxRunning) {
         isAjaxRunning.transport.abort();
         }
         isAjaxRunning = */
        new Ajax.Updater('walmart_attribute', '<?php echo Mage::helper("adminhtml")->getUrl('*/*/nodeIdAttributes')?>', {
            parameters: {evalJS: true, 'profile_id':<?php echo $profileId ?>, 'node_id': nodeId},
            onComplete: function (transport) {
                $('jet_attribute').update(transport.responseText);
                // Element.hide('loading-mask');
            },
        });
    }

</script>

<script type="text/javascript">
    function removeValidationMessage() {
        if (document.getElementById("advice-c_class_map-c_id_map")) {
            var elem = document.getElementById("advice-c_class_map-c_id_map");
            elem.parentElement.removeChild(elem);
        }
    }

    function selectedValue(id) {
        if (document.getElementById(id)) {
            var f = document.getElementById(id);
            var strUser = f.options[f.selectedIndex].value;
            return strUser;
        }
        return false;
    }
    Validation.add("c_class_map", "jet doesn't entertain uploading product on root category . Plz choose desired child category", function () {
        var root = selectedValue('p_id_map');
        var parent = selectedValue('c_id_map');
        if (root && (parent != 'na'))return true;
        return false;
    });

    function childCategory(id, check) {
        var e = document.getElementById(id);
        var strUser = e.options[e.selectedIndex].value;

        if (check == 'parent') {
            removeValidationMessage();
            if ($('c_id_map') || (strUser == 'na')) {
                $('c_id_map').remove();
                if ($('sc_id_map')) {
                    $('sc_id_map').remove();
                }
            }
            if (strUser != 'na') {
                var content = new Element('select', {
                    'class': 'c_class_map',
                    'id': 'c_id_map',
                    'onchange': 'childCategory("c_id_map","child")'
                });
                content.insert(
                    new Element('option', {'value': 'na'}).update('Please Choose Child Category ..')
                );
                console.log(strUser);
                console.log(js_level_1);
                for (var key in js_level_1) {
                    if (key == strUser) {
                        for (var subkey in js_level_1[key]) {
                            if (subkey == parent) {
                                content.insert(new Element('option', {
                                    'value': subkey,
                                    'selected': 'selected'
                                }).update(js_level_1[key][subkey]));
                                $('custom_tab_text').value = parent;
                            } else {
                                content.insert(
                                    new Element('option', {'value': subkey}).update(js_level_1[key][subkey])
                                );
                            }
                        }
                    }
                    //content.setStyle({margin: '0 0 0 14'});
                    $('pro').insert(content);
                    $('c_id_map').setStyle({
                        'margin-right': '14px'
                    });
                }
            } else {
                $('custom_tab_text').value = '';
            }
        }
        if (check == 'child') {
            removeValidationMessage();
            if ($('sc_id_map') || (strUser == 'na')) {
                $('sc_id_map').remove();
            }
            if (strUser != 'na') {
                var content = new Element('select', {
                    'class': 'sc_class_map',
                    'id': 'sc_id_map',
                    'onchange': 'childCategory("sc_id_map","subchild")'
                });
                content.insert(new Element('option', {'value': 'na'}).update('Please Choose Child Category ..'));
                var show = false;
                for (var key in js_level_2) {
                    if (key == strUser) {
                        for (var subkey in js_level_2[key]) {
                            show = true;
                            if (subkey == child) {
                                content.insert(new Element('option', {
                                    'value': subkey,
                                    'selected': 'selected'
                                }).update(js_level_2[key][subkey]));
                                $('custom_tab_text').value = child;
                                strUser = subkey;
                            } else {
                                content.insert(new Element('option', {'value': subkey}).update(js_level_2[key][subkey]));
                            }
                        }
                    }
                }
                if (show == true) {
                    $('pro').insert(content);
                }
                $('custom_tab_text').value = strUser;
            }
            else {
                $('custom_tab_text').value = 'error';
            }
        }
        if (check == 'subchild') {
            removeValidationMessage();
            if (strUser != 'na') {
                $('custom_tab_text').value = strUser;
            }
            else {
                var f = document.getElementById('c_id_map');
                var strUser2 = f.options[f.selectedIndex].value;
                $('custom_tab_text').value = strUser2;
            }
        }

        //update category attribute
        updateCategoryAttribute();
    }

    var content = new Element('select', {
        'class': 'p_class_map',
        'id': 'p_id_map',
        'onchange': 'childCategory("p_id_map","parent")'
    });
    content.insert(new Element('option', {'value': 'na'}).update('Please Choose Category ..'));
    var js_level_0 = <?php echo $json_parent_arr ?>;
    var js_level_1 = <?php echo $json_child_arr ?>;
    var js_level_2 = <?php echo $json_subchild_arr ?>;
    var child = '<?php echo $child; ?>';
    var parent = '<?php echo $parent; ?>';
    var root = '<?php echo $root; ?>';

   
          for (var key in js_level_0) {
            if (key == root) {
                content.insert(new Element('option', {'value': key, 'selected': 'selected'}).update(js_level_0[key]));
            }
            else {
                content.insert(new Element('option', {'value': key}).update(js_level_0[key]));
            }
        }
   
  
    //content.setStyle({margin: '0 0 0 14'});

    if ($('pro')) {
        $('pro').insert(content);
    }

    var myElem = document.getElementById("p_id_map");
    if (myElem != null) {
        myElem.style.marginRight = "14px";
    }

    var myElem1 = document.getElementById("c_id_map");
    if (myElem1 != null) {
        myElem1.style.marginRight = "14px";
    }
    if (child != '') {
        childCategory('p_id_map', 'parent');
        childCategory('c_id_map', 'child')
    }
    else if (parent != '') {
        childCategory('p_id_map', 'parent')
    }

</script>


<?php /*add attribute mapping required/optional*/ ?>
<div style="" class="grid" id="category_info_tabs_jet_categorymapping_content">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">
                <?php echo Mage::helper('jet')->__('Jet / Magento Attribute Mapping (Required/ Variant mapping)') ?></h4>
            <div class="form-buttons"></div>
        </div>
        <div id="custom_category_tab_form" class="fieldset ">
            <p><?php echo Mage::helper('jet')->__('Map Attribute for jet and Magento attribute') ?></p>
            <div class="hor-scroll" id="jet_attribute" style="overflow: visible!important;">
                <?php echo $this->getChildHtml('required_attributes'); ?>
            </div>
        </div>
    </div>
</div>
