<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftwrap
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $linkedGiftWrap = $this->getLinkedGiftWrap(); ?>
<?php if (!is_null($linkedGiftWrap)) : ?>
    <div class="col1-set order-info-box" id="order-aw-giftwrap-box">
        <div class="col-1">
            <div class="box">
                <div class="box-title">
                    <h2><?php echo $this->__('Order Gift Wrap Options'); ?></h2>
                </div>
                <div class="box-content">
                    <table cellspacing="0" class="aw-giftwrap-details">
                        <tbody>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Wrapping products separately?'); ?></label></td>
                                <td class="value"><strong><?php echo $this->getIsWrappingProductsSeparatelyLabel(); ?></strong></td>
                            </tr>
                            <?php if ($this->canShowGiftMessage()) : ?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Gift Message'); ?></label></td>
                                <td class="value"><strong><?php echo $this->getGiftMessage(); ?></strong></td>
                            </tr>
                            <?php endif; ?>
                            <tr>
                                <td class="label"><label><?php echo $this->__('Gift Wrap'); ?></label></td>
                                <td class="value"><?php echo $this->getGiftWrapHtml(); ?></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>