<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php /** @var Amasty_Cart_Block_Catalog_Product_List_Upsell $this */
if (count($this->getItemCollection()->getItems())): ?>
<div class="am-upsell-title">
    <span class="am-title"><?php echo $this->__('Customers Also Bought')?></span>
</div>
<div class="block block-upsell" id="am-block-upsell">
    <div class="block-content">
        <?php $this->resetItemsIterator() ?>
        <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
            <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
                <?php if($_link=$this->getIterableItem()): ?>
                    <div class="product">
                        <a href="<?php echo $_link->getProductUrl() ?>"
                         title="<?php echo $this->htmlEscape($_link->getName()) ?>"
                         class="product-image">
                         <img
                         src="<?php echo $this->helper('catalog/image')->init($_link, 'thumbnail')
                         ->resize(199, 122); ?>"
                         width="199" height="122"
                         alt="<?php echo $this->htmlEscape($_link->getName()) ?>"
                         />
                     </a>
                     <p class="product-name">
                        <a href="<?php echo $_link->getProductUrl() ?>">
                            <?php echo $this->htmlEscape($_link->getName()) ?>
                        </a>
                    </p>

                    <span><?php echo $this->__('Price:') ?></span>
                    <?php echo $this->getPriceHtml($_link, true, '-upsell'); ?>
                    <?php if ($_link->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to cart') ?>" class="button add-tocart">
                         <?php echo $this->__('Add to cart') ?></button>
                     <?php else: ?>
                        <p class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></p>
                    <?php endif; ?>
                </div>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
</div>
<script type="text/javascript">
    AmAjaxShoppCartLoad('.amcart-upsell-block button.add-tocart');
</script>
</div>
<?php endif ?>