<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>
<?php /* Extensions placeholder */ ?>
<?php echo $this->getChildHtml('checkout.onepage.login.extra')?>
<div class="col2-set">
    <?php echo $this->getChildHtml('login_before')?>
    <div class="grid_4 alpha">
        <h3><?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?><?php echo $this->__('Checkout as a Guest, Register or Login') ?><?php else: ?><?php echo $this->__('Register to Create an Account') ?><?php endif; ?></h3>

        <?php //echo $this->getChildHtml('col1_before')?>

        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <!--<p><?php //echo $this->__('Register with us for future convenience:') ?></p>-->
        <?php else: ?>
            <p><strong><?php echo $this->__('Register and save time!') ?></strong><br />
            <?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul>
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
        <?php endif; ?>
        <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
            <ul class="form-list">
                <?php if( $this->getQuote()->isAllowedGuestCheckout() ): ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:guest" value="guest"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_GUEST): ?> checked="checked"<?php endif; ?> class="radio" /><label for="login:guest"><?php echo $this->__('Checkout as Guest') ?></label>
                </li>
                <?php endif; ?>
                <li class="control">
                    <input type="radio" name="checkout_method" id="login:register" value="register"<?php if($this->getQuote()->getCheckoutMethod()==Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER || !$this->getQuote()->isAllowedGuestCheckout()): ?> checked="checked"<?php endif ?> class="radio" /><label for="login:register"><?php echo $this->__('Register') ?></label>
                </li>
                <li class="control">
                    <input type="radio" name="checkout_method" id="alreadyregister" value="alreadyregister" class="radio" /><label for="alreadyregister"><?php echo $this->__('I already have an account Let me log in!') ?></label>
                </li>
              
            </ul>
            <!--
            <h4><?php echo $this->__('Register and save time!') ?></h4>
            <p><?php echo $this->__('Register with us for future convenience:') ?></p>
            <ul class="ul">
                <li><?php echo $this->__('Fast and easy check out') ?></li>
                <li><?php echo $this->__('Easy access to your order history and status') ?></li>
            </ul>
            -->
            
        <?php else: ?>
            <input type="hidden" name="checkout_method" id="login:register" value="register" checked="checked" />
        <?php endif; ?>
            

        <?php //echo $this->getChildHtml('col2_before')?>
        <div class="already_account">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <form id="login-form" action="<?php echo $this->getPostAction() ?>" method="post">
        <fieldset>
            <?php echo $this->getBlockHtml('formkey'); ?>
           <!-- <h4><?php //echo $this->__('Already registered?') ?></h4>
            <p><?php //echo $this->__('Please log in below:') ?></p>-->
            <ul class="form-list">
                <li>
                    <label for="login-email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="text" class="input-text required-entry validate-email" id="login-email" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" />
                    </div>
                </li>
                <li>
                    <label for="login-password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                    <div class="input-box">
                        <input type="password" class="input-text required-entry" id="login-password" name="login[password]" />
                    </div>
                </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
        </fieldset>
        </form>
        <div class="buttons-set" style="padding-left:10px;">
            <?php //echo $this->getChildHtml('persistent.remember.me'); ?>
            <div class="test_button"><input type="checkbox" name="persistent_remember_me" class="checkbox" id="remember_mewSsoEfOp0P" checked="checked" title="Remember Me"><label for="remember_mewSsoEfOp0P">Remember Me</label>
            <p class="required" style="float:right;"><?php echo $this->__('* Required Fields') ?></p>
            </div>
            <div class="clear"></div>
           <div> <a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="f-left"><?php echo $this->__('Forgot your password?') ?></a></div>
            <div class="clear"></div>
            <button type="submit" class="button" onclick="onepageLogin(this)"><span style="border:none;height:auto;"><span><?php echo $this->__('Continue') ?></span></span></button>
            
        </div>
        </div>
        <div class="buttons-set">
            <!--<p class="required">&nbsp;</p>-->

            <?php if ($this->getQuote()->isAllowedGuestCheckout()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo $this->__('Continue') ?></span></span></button>
            <?php elseif ($this->helper('checkout')->isCustomerMustBeLogged()): ?>
                <button id="onepage-guest-register-button" type="button" class="button" onclick="window.location='<?php echo $this->helper('checkout/url')->getRegistrationUrl();?>'"><span><span><?php echo $this->__('Register') ?></span></span></button>
            <?php else: ?>
                <button type="button" class="button" onclick="checkout.setMethod();"><span><span><?php echo ($this->getQuote()->isAllowedGuestCheckout() ? $this->__('Continue') : $this->__('Register')) ?></span></span></button>
            <?php endif; ?>

        </div>
    </div>
    <div class="grid_4 omega">
         <h3><?php echo $this->__('EXPRESS CHECKOUT') ?></h3>
         <ul class="form-list">
             <?php 
                    echo '<li>';
                        echo $this->getLayout()->createBlock('amazon_payments/button')->setTemplate('amazon_payments/onepage/button.phtml')->toHtml();
                    echo'</li>';
                    echo '<li>';
                        echo $this->getLayout()->createBlock('paypaluk/express_shortcut')->setTemplate('paypal/express/shortcut.phtml')->toHtml();
                        
                    echo '</li>';
                ?>
                 <p style="text-align: center;">
            <a data-action="checkout-form-submit" id="ec_shortcut_3203c2d7732403a5b011d27ccda21dde" href="https://www.zeusbeard.com/paypal/express/start/button/1/"><img src="https://fpdbs.paypal.com/dynamicimageweb?cmd=_dynamic-image&amp;buttontype=ecshortcut&amp;locale=en_US&amp;ordertotal=36.95&amp;pal=QF27X83GG2MB6" alt="Checkout with PayPal" title="Checkout with PayPal" style="width: 145px; height: 42px;"></a>
        </p>
         </ul>
    </div>
</div>
<div class="col2-set">
    <div class="grid_4 alpha">
        
    </div>
    <div class="grid_4 omega">
        
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    var loginForm = new VarienForm('login-form', true);
    $('login-email').observe('keypress', bindLoginPost);
    $('login-password').observe('keypress', bindLoginPost);
    function bindLoginPost(evt){
        if (evt.keyCode == Event.KEY_RETURN) {
            loginForm.submit();
        }
    }
    function onepageLogin(button)
    {
        if(loginForm.validator && loginForm.validator.validate()){
            button.disabled = true;
            loginForm.submit();
        }
    }
    jQuery("input[name='checkout_method']").click(function () {
    jQuery('.already_account').css('display', (jQuery(this).val() === 'alreadyregister') ? 'block':'none');
    jQuery('#onepage-guest-register-button').css('display', (jQuery(this).val() === 'alreadyregister') ? 'none':'block'); 
}); 



/* jQuery("#alreadyregister").on("change",function(){
    if(jQuery(this).prop("checked"))
       jQuery(".already_account").show();  
            jQuery("#onepage-guest-register-button").hide();  
}); */
//]]>
</script>
