<?php
/**
 * Bss BestSellers
 *
 * @category    design
 * @package     harbour_default
 */
?>
<?php
/**
 * Product list template
 *
 * @see Bss_Bestseller_Block_Bestsellers
 */
?>
<?php
    $_productCollection = $this->getBestsellerProducts(6);
    $_helper = $this->helper('catalog/output');
    $meigee_harbour_general = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_general');
	$meigee_harbour_appearance = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_appearance');
	$fancybox = $meigee_harbour_general['fancybox'];
    $categoryComplete = Mage::getModel('catalog/category')->load(Mage::getModel('catalog/layer')->getCurrentCategory()->getId());
	$random = rand(5,1500);
    if($categoryComplete->getMeigeeGridLayout()) {
        $grid = $categoryComplete->getMeigeeGridLayout();
    } else {
        $grid = $meigee_harbour_appearance['productlisting']['grid'];
    }
    $helpImg = $this->helper('ThemeOptionsHarbour/images');
	if($categoryComplete->getProductname()) {
        $productname = $categoryComplete->getProductname();
        if($productname == 2){$productname = 0;}
    } else {
        $productname = $meigee_harbour_appearance['productlisting']['productname'];
    }
	if($categoryComplete->getProductprice()) {
        $productprice = $categoryComplete->getProductprice();
        if($productprice == 2){$productprice = 0;}
    } else {
        $productprice = $meigee_harbour_appearance['productlisting']['productprice'];
    }
	if($categoryComplete->getAddtocart()) {
        $addtocart = $categoryComplete->getAddtocart();
        if($addtocart == 2){$addtocart = 0;}
    } else {
        $addtocart = $meigee_harbour_appearance['productlisting']['addtocart'];
    }
	if($categoryComplete->getCompareproducts()) {
        $compareproducts = $categoryComplete->getCompareproducts();
        if($compareproducts == 2){$compareproducts = 0;}
    } else {
        $compareproducts = $meigee_harbour_appearance['productlisting']['compareproducts'];
    }
	if($categoryComplete->getWishlist()) {
        $wishlist = $categoryComplete->getWishlist();
        if($wishlist == 2){$wishlist = 0;}
    } else {
        $wishlist = $meigee_harbour_appearance['productlisting']['wishlist'];
    }

	$labelsoptions = $meigee_harbour_general['productlabels'];
	$labelsType = $meigee_harbour_general['productlabels']['labelview'];
	$labelsPosition = $meigee_harbour_general['productlabels']['labelsposition'];
	$productOnlyXleft = $meigee_harbour_general['productlabels']['labelonlyxleft'];
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="block__title" align="center">
        <font face="Raleway, sans-serif" size="5" color="black"><?php echo $this->__('Top Sellers'); ?></font> <br><br>
    </div>
    <ul class="owl-carousel owl-theme owl-loaded owl-drag products-grid <?php echo ' '.$labelsType.' '.$labelsPosition; ?>">
        <?php $i=1; foreach ($_productCollection as $_product): ?>
        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

            <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?><?php if($labelsoptions['labelsorder'] == 'new_sale'):?> labels-new-sale<?php endif; ?>">
                <div class="alpha">
                    <div class="product-img-box">
                        <?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'new'); ?>
                        <?php if($productOnlyXleft and MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product)): ?>
                            <?php echo MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product); ?>
                        <?php else: ?>
                            <?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'sale'); ?>
                        <?php endif; ?>
                        <?php if ($this->displayProductStockStatus()): ?>
                            <?php if (!$_product->isAvailable()): ?>
                                <p class="availability out-of-stock listing"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                        <?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 420, null); ?>
                            <img id="product-collection-image-<?php echo $_product->getId(); ?>" <?php echo $helpImg->getImgSources($_product, 'small_image', 420, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        </a>
                        <?php  // Fancybox
                        if ($this->displayProductStockStatus()):
                            if ($_product->isAvailable()):
                                if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
                                    <a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('fancybox'); ?></a>
                                <?php 	endif;
                            endif;
                        endif; // End Fancybox ?>
                    </div>
                    <div class="product-info">
                        <?php $summaryData = Mage::getModel('review/review_summary')->setStoreId($storeId)->load($_product->getId());
                        if ($summaryData['rating_summary']):?>
                            <div class="ratings">
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $summaryData['rating_summary']; ?>%"></div>
                                </div>
                                <span class="rating-count"><?php echo $summaryData['reviews_count']. $this->__(' Reviews'); ?></span>
                            </div>
                        <?php endif; ?>
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <?php
                        // Provides extra blocks on which to hang some features for products in the list
                        // Features providing UI elements targeting this block will display directly below the product name
                        if ($this->getChild('name.after')) {
                            $_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
                            foreach ($_nameAfterChildren as $_nameAfterChildName) {
                                $_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
                                $_nameAfterChild->setProduct($_product);
                                echo $_nameAfterChild->toHtml();
                            }
                        }
                        ?>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                        <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId()?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                            <div class="actions">
                                <?php if(!$_product->isGrouped()): ?>
                                    <input type="text" name="qty" id="qty-<?php echo $_product->getId() ?>" maxlength="12" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
                                    <div class="quantity-buttons">
                                        <div class="quantity-increase" onclick="qtyUp(<?php echo $_product->getId() ?>)"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('increaseqty'); ?></div>
                                        <div class="quantity-decrease" onclick="qtyDown(<?php echo $_product->getId() ?>)"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('descreaseqty'); ?></div>
                                    </div>
                                <?php endif; ?>
                                <?php if(!$_product->canConfigure() && $_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>"
                                            onclick="this.form.submit()" class="button btn-cart">
                                        <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                    </button>
                                <?php elseif($_product->getStockItem() && $_product->getStockItem()->getIsInStock()): ?>
                                    <a title="<?php echo $this->quoteEscape($this->__('View Details')) ?>" class="button" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                            </div>
                        </form>
                    </div>
                </div>
            </li>
        <?php $i++; endforeach ?>
    </ul>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <script type="text/javascript">
        jQuery('.owl-carousel').owlCarousel({
            loop: false,
            lazyLoad: true,
            nav: true,
            slideBy: 3,
            responsive:{
                0:{
                    items:1,
                    margin: 0
                },
                600:{
                    items:3,
                    margin: 10
                },
                1000:{
                    items:3,
                    margin: 30
                }
            }
        })
        function qtyDown(id){
            var qty_el = document.getElementById('qty-'+id);
            var qty = qty_el.value;
            if( qty == 2) {
                jQuery('.quantity_box_button_down').css({
                    'visibility' : 'hidden'
                });
            }
            if( !isNaN( qty ) && qty > 0 ){
                qty_el.value--;
            }
            return false;
        }

        function qtyUp(id){
            var qty_el = document.getElementById('qty-'+id);
            var qty = qty_el.value;
            if( !isNaN( qty )) {
                qty_el.value++;
            }
            jQuery('.quantity_box_button_down').css({
                'visibility' : 'visible'
            });
            return false;
        }

    </script>
<?php endif; ?>
