<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
	$meigee_harbour_general = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_general');	
	$meigee_harbour_appearance = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_appearance');
	$fancybox = $meigee_harbour_general['fancybox'];
    $categoryComplete = Mage::getModel('catalog/category')->load(Mage::getModel('catalog/layer')->getCurrentCategory()->getId());
	$random = rand(5,1500);
    if($categoryComplete->getMeigeeGridLayout()) {
		$grid = $categoryComplete->getMeigeeGridLayout();
	} else {
    	$grid = $meigee_harbour_appearance['productlisting']['grid'];
    }
    $helpImg = $this->helper('ThemeOptionsHarbour/images');
	if($categoryComplete->getProductname()) {
		$productname = $categoryComplete->getProductname();
		if($productname == 2){$productname = 0;}
	} else {
    	$productname = $meigee_harbour_appearance['productlisting']['productname'];
    }
	if($categoryComplete->getProductprice()) {
		$productprice = $categoryComplete->getProductprice();
		if($productprice == 2){$productprice = 0;}
	} else {
    	$productprice = $meigee_harbour_appearance['productlisting']['productprice'];
    }
	if($categoryComplete->getAddtocart()) {
		$addtocart = $categoryComplete->getAddtocart();
		if($addtocart == 2){$addtocart = 0;}
	} else {
		$addtocart = $meigee_harbour_appearance['productlisting']['addtocart'];
    }
	if($categoryComplete->getCompareproducts()) {
		$compareproducts = $categoryComplete->getCompareproducts();
		if($compareproducts == 2){$compareproducts = 0;}
	} else {
		$compareproducts = $meigee_harbour_appearance['productlisting']['compareproducts'];
	}
	if($categoryComplete->getWishlist()) {
		$wishlist = $categoryComplete->getWishlist();
		if($wishlist == 2){$wishlist = 0;}
	} else {
		$wishlist = $meigee_harbour_appearance['productlisting']['wishlist'];
    }
	
	$labelsoptions = $meigee_harbour_general['productlabels'];
	$labelsType = $meigee_harbour_general['productlabels']['labelview'];
	$labelsPosition = $meigee_harbour_general['productlabels']['labelsposition'];
	$productOnlyXleft = $meigee_harbour_general['productlabels']['labelonlyxleft'];
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<section class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list<?php echo ' '.$labelsType.' '.$labelsPosition; ?>" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?><?php if($labelsoptions['labelsorder'] == 'new_sale'):?> labels-new-sale<?php endif; ?>">
            <?php // Product Image ?>
            <div class="grid_3 alpha">
                <div class="product-img-box">
					<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'new'); ?>
					<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product)): ?>
						<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product); ?>
					<?php else: ?>
						<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'sale'); ?>
					<?php endif; ?>
					<?php if ($this->displayProductStockStatus()): ?>
						<?php if (!$_product->isAvailable()): ?>
							<p class="availability out-of-stock listing"><span><?php echo $this->__('Out of stock') ?></span></p>
						<?php endif; ?>
					<?php endif; ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 420, null); ?>
						<img id="product-collection-image-<?php echo $_product->getId(); ?>" <?php echo $helpImg->getImgSources($_product, 'small_image', 420, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
					</a>
                    <?php // Fancybox
					if ($this->displayProductStockStatus()):
						if ($_product->isAvailable()):
							if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
								<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('fancybox'); ?></a>
                    <?php 
							endif; 
						endif;
					endif; //End Fancybox ?>
                </div>
            </div>
            <?php // Product description ?>
            <div class="omega right-col">
				<div class="product-shop">
					<?php if($productname): ?>
						<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
					<?php endif; ?>
					<?php
						// Provides extra blocks on which to hang some features for products in the list
						// Features providing UI elements targeting this block will display directly below the product name
						if($this->getChild('name.after')){
							$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
							foreach ($_nameAfterChildren as $_nameAfterChildName) {
								$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
								$_nameAfterChild->setProduct($_product);
								echo $_nameAfterChild->toHtml();
							}
						}
					?>
					<?php if($_product->getRatingSummary()): ?>
						<?php echo $this->getReviewsSummaryHtml($_product) ?>
					<?php endif; ?>
					<?php if(!$_product->isSaleable()): ?>
						<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
					<?php endif; ?>
					<?php if($productprice): ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
					<?php endif; ?>
					<div class="desc std">
						<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
					</div>
					<?php if($_product->isSaleable()): ?>
						<?php if($addtocart){ ?>
							 <div class="button-holder"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
						<?php } ?>
					<?php endif; ?>
					<?php if($wishlist || $compareproducts){?>
						<ul class="add-to-links">
							<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
								<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('wishlist'); ?></a></li>
							<?php endif; ?>
							<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
								<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('compare'); ?></a></li>
							<?php endif; ?>
						</ul>
					<?php } ?>
				</div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">
		decorateList('products-list', 'none-recursive')
		jQuery(document).ready(function(){
			geListColumn();
		});
	</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>

	<ul class="products-grid <?php echo 'grid-'.$grid.'-columns'; echo ' '.$labelsType.' '.$labelsPosition; ?>">
    <?php $i=1; foreach ($_productCollection as $_product): ?>
		<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <li class="item<?php if($labelsoptions['labelsorder'] == 'new_sale'):?> labels-new-sale<?php endif; ?>">
				<div class="product-container">
					<div class="product-img-box">
						<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'new'); ?>
						<?php if($productOnlyXleft and MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product)): ?>
							<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductOnlyXleft($_product); ?>
						<?php else: ?>
							<?php echo MAGE::helper('ThemeOptionsHarbour')->getProductLabels($_product, 'sale'); ?>
						<?php endif; ?>
						<?php if ($this->displayProductStockStatus()): ?>
							<?php if (!$_product->isAvailable()): ?>
								<p class="availability out-of-stock listing"><span><?php echo $this->__('Out of stock') ?></span></p>
							<?php endif; ?>
						<?php endif; ?>
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php /* Hover Image */ echo $helpImg->getHoverImage($_product, 'small_image', 420, null); ?>
							<img id="product-collection-image-<?php echo $_product->getId(); ?>" <?php echo $helpImg->getImgSources($_product, 'small_image', 420, null); ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
						</a>
						<?php  // Fancybox
						if ($this->displayProductStockStatus()):
							if ($_product->isAvailable()):
								if ($fancybox['fancybox_status'] && $fancybox['fancybox_listing'] == 1): ?>
									<a class="fancybox category-gallery" title="<?php echo $_productNameStripped; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('fancybox'); ?></a>
						<?php 	endif;
							endif;
						endif; // End Fancybox ?>
					</div><?php $this->helper('yotpo')->showBottomline($this, $_product); ?>
					<div class="product-info">
						<?php if($productname): ?>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
						<?php endif; ?>
						<?php
							// Provides extra blocks on which to hang some features for products in the list
							// Features providing UI elements targeting this block will display directly below the product name
							if($this->getChild('name.after')){
								$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
								foreach ($_nameAfterChildren as $_nameAfterChildName) {
									$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
									$_nameAfterChild->setProduct($_product);
									echo $_nameAfterChild->toHtml();
								}
							}
						?>
						<?php if($_product->getRatingSummary()): ?>
							<?php echo $this->getReviewsSummaryHtml($_product) ?>
						<?php endif; ?>
						<?php if($productprice): ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						<?php endif; ?>
					</div>
					<?php if($_product->isSaleable()): ?>
						<?php if($addtocart){ ?>
							<div class="button-holder"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
						<?php } ?>
					<?php endif; ?>
					<?php if ($wishlist || $compareproducts) { ?>
						<div class="product-buttons">
							<ul class="add-to-links">
								<?php if ($this->helper('wishlist')->isAllow() and $wishlist) : ?>
									<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('wishlist'); ?></a></li>
								<?php endif; ?>
								<?php if($_compareUrl=$this->getAddToCompareUrl($_product) and $compareproducts): ?>
									<li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo MAGE::helper('ThemeOptionsHarbour')->getIcon('compare'); ?></a></li>
								<?php endif; ?>
							</ul>
						</div>
					<?php } ?>
				</div>
            </li>
            <?php $i++; endforeach ?>
    </ul>
    <script type="text/javascript">
		decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])
		isotopLoader();
	</script>
    <?php endif; ?>
	<script type="text/javascript">
		/* list column */
		function geListColumn(callback){
			mainContainer = jQuery('.main-container');
			rightCol = jQuery('.products-list .right-col');
			
			if(jQuery('.col-main').hasClass('grid_12')){
				rightCol.addClass('grid_9');
			}else if(mainContainer.hasClass('col3-layout')){
				rightCol.addClass('grid_3');
			}else{
				rightCol.addClass('grid_6');
			}
			
			try{
				callback();
			}catch(err){}
			labelsHeight();
		}
	</script>
    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</section>
<?php endif; ?>
<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')){
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName){
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>