<?php
/**
 * Magento
 *
 * @category    design
 * @package     meigeetheme_default
 * @copyright   Copyright (c) 2012 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<?php
	$meigee_harbour_appearance = MAGE::helper('ThemeOptionsHarbour')->getThemeOptionsHarbour('meigee_harbour_appearance');
	$cartpage = $meigee_harbour_appearance['layout']['cartpage'];
?>
<div class="cart cart-2">
	<div class="page-title title-buttons">
		<h1><?php echo $this->__('Shopping Cart') ?></h1>
		<?php if(!$this->hasError()): ?>
			<ul class="checkout-types top-checkout">
	            <?php foreach ($this->getMethods('top_methods') as $method): ?>
	                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
	                    <li><?php echo $methodHtml; ?></li>
	                <?php endif; ?>
	            <?php endforeach; ?>
	        </ul>
		<?php endif; ?>
		<br class="clear" />
	</div>
	<div class="grid_9 alpha">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<?php echo $this->getChildHtml('form_before') ?>
		<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
			<?php echo $this->getBlockHtml('formkey'); ?>
			<fieldset>
				<table id="shopping-cart-table" class="data-table cart-table">
				<col />
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
					<col width="1" />
				<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
				<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
					<col width="1" />
				<?php endif; ?>
				<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
					<thead>
						<tr>
							<th rowspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
							<th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('Unit Price') ?></span></th>
							<th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
							<th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
						</tr>
						<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
						<tr>
							<th class="a-center"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
							<th class="a-center"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
							<th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
						</tr>
						<?php endif; ?>
					</thead>
					<tfoot>
						<tr class="buttons-row">
							<td colspan="50" class="a-right buttons">
								<div>
									<?php if($this->getContinueShoppingUrl()): ?>
										<button type="button" title="<?php echo $this->__('Continue Shopping') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"><span><span><?php echo $this->__('Continue Shopping') ?></span></span></button>
									<?php endif; ?>
									<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-clear"><span><span><?php echo $this->__('Clear Shopping Cart'); ?></span></span></button>
									<button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><span><span><?php echo $this->__('Update Shopping Cart'); ?></span></span></button>
								</div>
							</td>
						</tr>
					</tfoot>
					<tbody>
					<?php foreach($this->getItems() as $_item): ?>
						<?php echo $this->getItemHtml($_item) ?>
					<?php endforeach ?>
					</tbody>
				</table>
				<script type="text/javascript">decorateTable('shopping-cart-table')</script>
			</fieldset>
		</form>
		<?php 
			$totals =  Mage::getSingleton('checkout/session')->getQuote()->getTotals();
			$total =  35 - $totals['subtotal']->getValue();
		?>
		<?php if($totals['subtotal']->getValue() < 35) : ?>
		<div class="shipping-mess">
			<p class="shipping-total"><span class="messchamthan">!</span> You're only <?php echo Mage::helper('core')->currency($total,true,false) ?> away from Free Shipping!</p>
		</div>
		<?php endif ?>
		
		<div class="clear"></div>
		<?php echo $this->getChildHtml('crosssell_big') ?>
	</div>
	<aside class="grid_3 omega payment_top">
		<?php if (!$this->getIsVirtual()): ?>
			<?php echo $this->getChildHtml('shipping'); ?>
		<?php endif; ?>
		<section class="totals">
			<!-- <div class="totals"> -->
				<header class="cart-blocks-title">
					<h2><?php echo $this->__('Total') ?></h2>
				</header>
				<div class="totals-border">
					<div class="totals-wrapper"><?php echo $this->getChildHtml('totals'); ?></div>
					<?php if(!$this->hasError()): ?>
					<ul class="checkout-types">
					<?php foreach ($this->getMethods('methods') as $method): ?>
						<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
						<li><?php echo $methodHtml; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
					</ul>
					<?php endif; ?>
				</div>
			<!-- </div> -->
		</section>
		<div class="clear"></div>

		<section class="block-colright payment-wrap">
			<div class='harbour-payment'>
            	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-payment-block')->toHtml(); ?> 
            </div>
        </section>
        
        <div class="clear"></div>

        <section class="block-colright needhelp-wrap hide-tablet">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-needhelp-block')->toHtml(); ?> 
        </section>


	</aside>
	<div class="couponandgifcart grid_9">
		<div class='gc-coupon clearfix'>
			<div class="giftcart">
				<?php if(Mage::helper('checkout/cart')->getItemsCount()): ?>
				<?php 
					$block = Mage::app()->getLayout()->createBlock('aw_giftcard/frontend_checkout_cart_giftcard');
	            	echo $block->toHtml();
				 ?>
				<?php endif; ?>
			</div>
			<div class="counpon">
				<?php if($this->getChildHtml('coupon')): ?>
					<section class="coupon">
						<?php echo $this->getChildHtml('coupon') ?>
					</section>
				<?php endif; ?>
			</div>
		</div>
		<div class="clear"></div>
		<section class="block-colright needhelp-wrap display-tablet">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-needhelp-block')->toHtml(); ?> 
        </section>

		<div class="grid_9 alpha block-usp-wrap hide-tablet">
        	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-usp-block')->toHtml(); ?>
    	</div>

    	


	</div>

	<div class="grid_9 alpha block-usp-wrap display-tablet">
        	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('harbour-usp-block')->toHtml(); ?>
    	</div>
	

	<aside class="omega payment_bot">
		<?php if (!$this->getIsVirtual()): ?>
			<?php echo $this->getChildHtml('shipping'); ?>
		<?php endif; ?>
		<section class="totals">
			<!-- <div class="totals"> -->
				<header class="cart-blocks-title">
					<h2><?php echo $this->__('Total') ?></h2>
				</header>
				<div class="totals-border">
					<div class="totals-wrapper"><?php echo $this->getChildHtml('totals'); ?></div>
					<?php if(!$this->hasError()): ?>
					<ul class="checkout-types">
					<?php foreach ($this->getMethods('methods') as $method): ?>
						<?php if ($methodHtml = $this->getMethodHtml($method)): ?>
						<li><?php echo $methodHtml; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
					</ul>
					<?php endif; ?>
				</div>
			<!-- </div> -->
		</section>
		<div class="clear"></div>
	</aside>
	<div class="clear"></div>
<div class="clear"></div>
</div>
<script type="text/javascript">
    jQuery(document).ready(function(){
        var myVar = setInterval(function(){ 
            if (jQuery('.top-checkout .amazon-pay-button img').length ){
                jQuery('.top-checkout .amazon-pay-button img').clone().appendTo('.omega .amazon-pay-button');
                jQuery('.omega .amazon-pay-button img').click(function(){
                    jQuery('.top-checkout .amazon-pay-button img').click();
                });
                myStopFunction();
            }
        }, 1000);

        function myStopFunction() {
            clearInterval(myVar);
        }
    });
</script>
<script type="text/javascript">
        jQuery(document).ready(function() {
            var windowWidth = jQuery(window).width();
            function setToogle() {
            	jQuery('.giftcard-item-button').on('click', function() {
	                if(jQuery('.discount.aw_giftcard').hasClass('isset_plus')){
	                    jQuery('.giftcard-item-button #plus-2').css('display','none');
	                    jQuery('.giftcard-item-button #minus-2').css('display','block');
	                    jQuery('.discount.aw_giftcard').removeClass('isset_plus');
	                }else {
	                    jQuery('.giftcard-item-button #plus-2').css('display','block');
	                    jQuery('.giftcard-item-button #minus-2').css('display','none');
	                    jQuery('.discount.aw_giftcard').addClass('isset_plus');
	                }
	            });
	            jQuery('.coupon-item-button').on('click', function() {
	                if(jQuery('.coupon .discount').hasClass('isset_plus')){
	                    jQuery('.coupon-item-button #plus-1').css('display','none');
	                    jQuery('.coupon-item-button #minus-1').css('display','block');
	                    jQuery('.coupon .discount').removeClass('isset_plus');
	                }else {
	                    jQuery('.coupon-item-button #plus-1').css('display','block');
	                    jQuery('.coupon-item-button #minus-1').css('display','none');
	                    jQuery('.coupon .discount').addClass('isset_plus');
	                }
	            });
            }
            if(windowWidth < 768) {
                jQuery('.discount.aw_giftcard').addClass('isset_plus');
                jQuery('.giftcard-item-button #minus-2').css('display','none');
                jQuery('#aw_giftcard-form').css('display','none');
                jQuery('.coupon .discount').addClass('isset_plus');
                jQuery('.discount #minus-1').css('display','none');
                jQuery('.discount .discount-form').css('display','none');
            }else {
            	jQuery('.giftcard-item-button #plus-2').css('display','none');
                jQuery('.giftcard-item-button #minus-2').css('display','none');
                jQuery('.coupon-item-button #plus-1').css('display','none');
                jQuery('.coupon-item-button #minus-1').css('display','none');
            }
            setToogle();
            jQuery('.giftcard-item-button').on('click', function() {
            	jQuery('#aw_giftcard-form').slideToggle();
            });
            jQuery('.coupon-item-button').on('click', function() {
            	jQuery('.discount .discount-form').slideToggle();
            });
			jQuery(window).resize(function() {
				var windowWidth = jQuery(window).width();
	            if(windowWidth > 767) {
	            	jQuery('.giftcard-item-button #plus-2').css('display','none');
                    jQuery('.giftcard-item-button #minus-2').css('display','none');
                    jQuery('.coupon-item-button #plus-1').css('display','none');
                    jQuery('.coupon-item-button #minus-1').css('display','none');
                    jQuery('#aw_giftcard-form').css('display','block');
                    jQuery('.discount .discount-form').css('display','block');
	            	jQuery('.discount.aw_giftcard').removeClass('isset_plus');
	            	jQuery('.coupon .discount').removeClass('isset_plus');
	            }else {
	            	setToogle();
	            	jQuery('.discount.aw_giftcard').addClass('isset_plus');
	            	jQuery('.giftcard-item-button #plus-2').css('display','block');
	                jQuery('.giftcard-item-button #minus-2').css('display','none');
	                jQuery('#aw_giftcard-form').css('display','none');
	                jQuery('.coupon .discount').addClass('isset_plus');
	                jQuery('.discount #plus-1').css('display','block');
	                jQuery('.discount #minus-1').css('display','none');
	                jQuery('.discount .discount-form').css('display','none');
	            }
	        });
	    });
</script>