<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftwrap
 * @version    1.1.1
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $linkedGiftWrap = $this->getLinkedGiftWrap(); ?>
<?php if (!is_null($linkedGiftWrap)) : ?>
    <?php if (Mage::helper('aw_giftwrap')->isMageVersionLessOrEqualThan()) : ?>
        <?php $headerStyle = 'background-color:#d9e5ee;padding: 5px 9px 6px 9px;border:1px solid #bebcb7;border-bottom:none;line-height:1em;'; ?>
        <?php $bodyStyle = ' padding:7px 9px 9px 9px;border:1px solid #bebcb7;border-top:0;background:#f8f7f5;'; ?>
    <?php else : ?>
        <?php $headerStyle = 'background-color:#EAEAEA;font-size:13px;padding:5px 9px 6px 9px;line-height: 1em;'; ?>
        <?php $bodyStyle = 'font-size:12px;padding:7px 9px 9px 9px;border-left:1px solid #EAEAEA;border-bottom:1px solid #EAEAEA;border-right:1px solid #EAEAEA;'; ?>
    <?php endif; ?>
    <table id="order-aw-giftwrap-box" cellspacing="0" cellpadding="0" border="0" width="650">
        <thead>
            <tr>
                <th align="left" width="650" style="<?php echo $headerStyle; ?>">
                    <?php echo $this->__('Order Gift Wrap Options:'); ?>
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td valign="top" style="<?php echo $bodyStyle; ?>">
                    <table cellspacing="0" class="aw-giftwrap-details">
                        <tbody>
                        <tr>
                            <td style="vertical-align: top;padding-right: 15px;"><label><?php echo $this->__('Wrapping products separately?'); ?></label></td>
                            <td style="vertical-align: top;width: 400px;"><strong><?php echo $this->getIsWrappingProductsSeparatelyLabel(); ?></strong></td>
                        </tr>
                        <?php if ($this->canShowGiftMessage()) : ?>
                            <tr>
                                <td style="vertical-align: top;padding-right: 15px;"><label><?php echo $this->__('Gift Message'); ?></label></td>
                                <td style="vertical-align: top;width: 400px;"><strong><?php echo $this->getGiftMessage(); ?></strong></td>
                            </tr>
                        <?php endif; ?>
                        <tr>
                            <td style="vertical-align: top;padding-right: 15px;"><label><?php echo $this->__('Gift Wrap'); ?></label></td>
                            <td style="vertical-align: top;width: 400px;"><?php echo $this->getGiftWrapHtml(); ?></td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </tbody>
    </table>
    <br>
<?php endif; ?>