<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
$storeCode1 = Mage::app()->getStore()->getCode();
?>
<div class="account-login<?php if (!$this->helper('customer')->isRegistrationAllowed()) echo ' login-only' ?> pslogin-form">
    <div class="page-title">
        <h1><?php if ($this->helper('customer')->isRegistrationAllowed()): ?>
                <?php echo $this->__('Login or Create an Account') ?>
            <?php else: ?>
                <?php echo $this->__('Login'); ?>
            <?php endif; ?></h1>
    </div>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form" class="scaffold-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="grid_6 alpha new-users">
            <div class="content">
                <?php
                if ($storeCode1 == 'wholesale') {
                    echo '<h2>'.$this->__('New Wholesalers').'</h2>';
                    echo '<p>'.$this->__("Zeus Wholesalers get access to our exclusive website just for retailers—complete with quick one-page ordering, official Zeus marketing collateral, and sneak peeks at our next great product. If you're ready to become a Zeus Wholesaler, click below to apply and get started.").'</p>';
                }else {
                    echo '<h2>'.$this->__('New Customers').'</h2>';
                    echo '<p>'.$this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.').'</p>';
                }
                ?>
            </div>
            <div class="buttons-set">
                <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo Mage::helper('persistent')->getCreateAccountUrl($this->getCreateAccountUrl()) ?>';"><span><span>
                <?php
                if ($storeCode1 == 'wholesale') {
                    echo $this->__('Apply for Zeus Wholesale');
                }else {
                    echo $this->__('Create an Account');
                }
                ?>
                </span></span></button>
            </div>
            <?php if (Mage::helper('pslogin')->modulePositionEnabled('login') && Mage::helper('pslogin')->hasButtons()) : ?>
                    <div class="pslogin-spacer pslogin-clearfix"> 
                    <h2>Login with your social account</h2>
                        <!-- <table>
                            <tr>
                                <td><div class="pslogin-border"></div></td>
                                <td class="pslogin-bordertext w25"><?php echo $this->__('OR'); ?></td>
                                <td><div class="pslogin-border"></div></td>
                            </tr>
                        </table> -->
                    </div>
                <?php echo $this->getChildHtml('pslogin_buttons'); ?>
            <?php endif; ?>
        </div>
        <div class="grid_6 omega registered-users">
            <div class="content">
                <?php
                if ($storeCode1 == 'wholesale') {
                    echo '<h2>'.$this->__('Registered Wholesalers').'</h2>';
                }else {
                    echo '<h2>'.$this->__('Registered Customers').'</h2>';
                }
                ?>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me'); ?>
                </ul>
                <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
            <div class="buttons-set">
                <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
                <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
            </div>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script>
</div>
