<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_SocialLogin
 * @copyright   Copyright (c) 2014 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<!DOCTYPE HTML>
<html>
	<head>
		<title><?php echo $this->getTitle(); ?></title>
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/plumrocket/pslogin/pslogin.css'); ?>" media="all">
	</head>
	<body class="pslogin-openid <?php echo $this->getProvider(); ?>">
		<form method="post" action=".">
			<div class="network-logo"></div>
			<div class="form-wrapper">
				<?php echo $this->getTitle(); ?><br/>
			    <input type="text" name="openid_id" value="" size="45" />
			    <br />
			    <div class="ajax-loader">
			    	<div class="error-text"><?php echo $this->getErrorText(); ?></div>
			    	<div class="image-gif"></div>
			    </div>
			    <input type="submit" name="submit" onclick="document.getElementsByClassName('error-text')[0].style.display = 'none'; document.getElementsByClassName('image-gif')[0].style.display = 'block';" value="Login" />
		    </div>
		</form>

	</body>
</html>