<?php $product = Mage::registry('current_product'); ?>

<script type="text/javascript">
var google_tag_params = {
ecomm_prodid: "<?php echo $product->getSku(); ?>",
ecomm_pagetype: "product",
ecomm_totalvalue: <?php echo $product->getFinalPrice(); ?>,
};
</script>
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 976640032;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/976640032/?guid=ON&amp;script=0"/>
</div>
</noscript>
