<?php
/**
  * CedCommerce
  *
  * NOTICE OF LICENSE
  *
  * This source file is subject to the End User License Agreement (EULA)
  * that is bundled with this package in the file LICENSE.txt.
  * It is also available through the world-wide-web at this URL:
  * http://cedcommerce.com/license-agreement.txt
  *
  * @category    Ced
  * @package     Ced_Jet
  * @author      CedCommerce Core Team <connect@cedcommerce.com >
  * @copyright   Copyright CEDCOMMERCE (http://cedcommerce.com/)
  * @license      http://cedcommerce.com/license-agreement.txt
  */
?>

<div class="entry-edit" id="support_kb">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Cedcommerce Support</h4>
		</div>
		<div class="fieldset">
			<a target="_blank" href="http://support.cedcommerce.com/kb/faq.php?cid=9">Jet Integration Knowledge base</a>	
        </div>
		   
</div>
<div class="entry-edit" id="support_kb">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Documentation</h4>
		</div>
		<div class="fieldset">
			<a target="_blank" href="http://docs.cedcommerce.com/magento/jet-magento-integration-guide-0-3-4-2">Jet Integration Extension User  Guide</a>	
			<a target="_blank" href="http://docs.cedcommerce.com/magento/jet-magento-integration-0-3-4-release-notes-2">Jet Magento Integration Version Release Notes</a>
        </div>	    
            
</div>
<div class="entry-edit" id="support_kb">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Need Help! Request Support</h4>
		</div>
		<div class="fieldset">
			<a target="_blank" href="http://support.cedcommerce.com/open.php">Create Ticket</a>	
			
        </div>	    
            
</div>

<div class="entry-edit" id="integration_video">

        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Integration Video from Jet.com</h4>
		</div>
		<div class="fieldset">
			<ul>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/sFOhhX0iAOw">Integration Process Introduction of Jet.com</a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/e0jg73m1L_I">API Overview</a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/aKEF2kBNs6A">Merchant Basic Information Setup at Partner Portal</a>
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products API call test</a>
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
						<a target="_blank" href="https://youtu.be/4UsuZux4vug">Products Overview</a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/MVHCjB7jhww">Products API call test</a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/q1rW7wFzBAg">Orders Setup</a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://youtu.be/7ZUjRQLTxUw">Returns Setup </a>	
				</li>
				<li style="margin-bottom:10px;margin-top:10px;">
					<a target="_blank" href="https://developer.jet.com/v1.0/page/integration-videos	">Integration Videos </a>	
				</li>
			</ul>
		</div>	
		
</div>