<?php
/**
 * Magmodules.eu - http://www.magmodules.eu.
 *
 * NOTICE OF LICENSE
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://www.magmodules.eu/MM-LICENSE.txt
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magmodules.eu so we can send you a copy immediately.
 *
 * @category      Magmodules
 * @package       Magmodules_Richsnippets
 * @author        Magmodules <info@magmodules.eu>
 * @copyright     Copyright (c) 2017 (http://www.magmodules.eu)
 * @license       https://www.magmodules.eu/terms.html  Single Service License
 */
?>
<?php if ($crumbs && is_array($crumbs)) { ?>
    <?php if (Mage::getStoreConfig('snippets/system/breadcrumbs_markup') == 'schema') { ?>
        <div class="grid-full breadcrumbs">
            <ul itemscope itemtype="http://schema.org/BreadcrumbList">
                <?php $i = 0;
                foreach ($crumbs as $_crumbName => $_crumbInfo) { ?>
                    <li class="<?php echo $_crumbName ?>" itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                        <?php if ($_crumbInfo['first']) { ?>
                            <?php $first_label = $this->htmlEscape($_crumbInfo['label']); ?>
                            <a itemprop="item" href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><span itemprop="name"><?php echo Mage::helper('snippets')->getFirstBreadcrumbTitle($first_label) ?></span></a>
                        <?php } else { ?>
                            <?php if ($_crumbInfo['link']) { ?>
                                <a itemprop="item" href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>"><span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span></a>
                            <?php } elseif ($_crumbInfo['last']) { ?>
                                <strong><span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span></strong>
                            <?php } else { ?>
                                <span itemprop="name"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></span>
                            <?php } ?>
                        <?php } ?>
                        <?php if (!$_crumbInfo['last']) { ?>
                            &nbsp; &raquo;
                        <?php } ?>
                        <meta property="position" content="<?php echo $i; ?>">
                    </li>
                    <?php $i++;
                } ?>
            </ul>
        </div>
    <?php } else { ?>
        <div class="grid-full breadcrumbs">
            <ul>
                <?php foreach ($crumbs as $_crumbName => $_crumbInfo) { ?>
                    <li class="<?php echo $_crumbName ?>">
                        <?php if ($_crumbInfo['first']) { ?>
                            <?php $first_label = $this->htmlEscape($_crumbInfo['label']); ?>
                            <span typeof="v:Breadcrumb">
                                <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo Mage::helper('snippets')->getFirstBreadcrumbTitle($first_label) ?></a>
                            </span>
                        <?php } else { ?>
                            <?php if ($_crumbInfo['link']) { ?>
                                <span typeof="v:Breadcrumb">
                                    <a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
                                </span>
                            <?php } elseif ($_crumbInfo['last']) { ?>
                                <strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
                            <?php } else { ?>
                                <?php echo $this->htmlEscape($_crumbInfo['label']) ?>
                            <?php } ?>
                        <?php } ?>
                        <?php if (!$_crumbInfo['last']) { ?>
                            &nbsp; &raquo;
                        <?php } ?>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>
<?php } ?>