<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Points
 * @version    1.7.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$summaryForCustomer = $this->getSummaryForCustomer();
$textForPoints = Mage::helper('points/config')->getPointUnitName();
$defaultValue = Mage::app()->getRequest()->getParam('payment[points_amount]');
?>

<dl class="sp-methods" id="checkout-payment-method-load">
<?php if ($this->pointsSectionAvailable()): ?>
    <dt>
        <input type="checkbox" name="payment[use_points]" id="use_points" checked="checked" />
        <label for="use_points"><?php echo $this->__('Use my %s', $textForPoints) ?></label>
    </dt>
    <dt>
        <input type="text" name="payment[points_amount]" value ="<?php echo $defaultValue; ?>" id="points_amount" onchange="awPointsConfig.pointsAmountChanged()" />
        <label for="points_amount"><?php echo Mage::helper('points')->__('of %s %s (%s) available', $summaryForCustomer->getPoints(), $textForPoints, $this->getMoneyForPoints()) ?></label>
    </dt>
<?php endif; ?>
<?php $oneMethod = false;?>
<?php foreach ($this->getMethods() as $_method): $_code = $_method->getCode() ?>
    <dt>
        <?php if (sizeof($this->getMethods()) > 1): ?>
            <input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" title="<?php echo $this->htmlEscape($_method->getTitle()) ?>" onclick="payment.switchMethod('<?php echo $_code ?>')"<?php if ($this->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?> class="radio" />
        <?php else: ?>
            <?php $oneMethod = $_method->getCode();?>
            <span class="no-display"><input id="p_method_<?php echo $_code ?>" value="<?php echo $_code ?>" type="radio" name="payment[method]" checked="checked" class="radio" /></span>
        <?php endif; ?>
        <label for="p_method_<?php echo $_code ?>"><?php echo $this->getMethodTitle($_method) ?> <?php echo $this->getMethodLabelAfterHtml($_method) ?></label>
    </dt>
    <?php if ($html = $this->getPaymentMethodFormHtml($_method)): ?>
        <dd>
            <?php echo $html; ?>
        </dd>
    <?php endif; ?>
<?php endforeach; ?>
</dl>
<?php echo $this->getChildChildHtml('additional'); ?>
<script type="text/javascript">
    //<![CDATA[
    <?php echo $this->getChildChildHtml('scripts'); ?>
    // payment.init();
    <?php if (is_string($oneMethod)): ?>
    payment.switchMethod('<?php echo $oneMethod ?>');
    <?php endif; ?>
    //]]>
</script>
<?php if ($this->pointsSectionAvailable()): ?>
    <script type="text/javascript">
        //<![CDATA[
        var awPointsConfig = {
            customerPoints: <?php echo $summaryForCustomer->getPoints() ?>,
            neededPoints: <?php echo $this->getNeededPoints() ?>,
            limitedPoints: <?php echo $this->getLimitedPoints() ?>,
            spendRatePoints: <?php echo $this->getSpendRatePoints() ?>,
            isPointsSubstracted: false,
            pointsInMoneyApplied: <?php echo (int)$this->getQuote()->getBaseMoneyForPoints() ?>,
            pointsInMoneyDelta: 0,
            pointsInMoneyUsed: 0,

            init: function(){
                $('use_points').disabled = $('points_amount').disabled = false;
                $('points_amount').value = Math.abs(Math.min(this.customerPoints, this.neededPoints, this.limitedPoints)).toFixed(0);
                this.pointsInMoneyUsed = $('points_amount').value * this.spendRatePoints;
                this.initObserver();
                this.checkStoreCredit();
            },

            pointsAmountChanged: function() {
                var points_amount = $('points_amount').value;
                if (isNaN(points_amount)) points_amount = 0;
                points_amount = Math.min(Math.abs(points_amount), this.customerPoints, this.neededPoints, this.limitedPoints);
                $('points_amount').value = Math.abs(points_amount).toFixed(0);

                this.checkStoreCredit();
            },

            /*AW_StoreCredit compatibility*/
            checkStoreCredit: function() {
                if (typeof(storeCreditManager) != "undefined") {
                    if ($('use_points').checked) {
                        this.pointsInMoneyDelta = this.pointsInMoneyUsed - $('points_amount').value * this.spendRatePoints;
                    }
                    this.pointsInMoneyUsed = $('points_amount').value * this.spendRatePoints;

                    storeCreditManager.quoteBaseGrandTotal += this.pointsInMoneyApplied;
                    this.pointsInMoneyApplied = 0;
                    storeCreditManager.quoteBaseGrandTotal += this.pointsInMoneyDelta;
                    this.pointsInMoneyDelta = 0;

                    if (!this.isPointsSubstracted && $('use_points').checked) {
                        storeCreditManager.quoteBaseGrandTotal -= this.pointsInMoneyUsed;
                        this.isPointsSubstracted = true;
                    }

                    if (this.isPointsSubstracted && !$('use_points').checked) {
                        storeCreditManager.quoteBaseGrandTotal += this.pointsInMoneyUsed;
                        this.isPointsSubstracted = false;
                    }

                    storeCreditManager.switchStorecreditCheckbox();
                }
            },

            initObserver: function(){
                var me = this;
                Event.observe($('use_points'), "click", function(){
                    me.checkStoreCredit();
                });
            }
        };

        if (payment) {
            payment.addAfterInitFunction('awpoints', awPointsConfig.init.bind(awPointsConfig));
        }
        //]]>
    </script>
<?php endif; ?>